# frozen_string_literal: true

require 'rails_helper'

feature 'Add files to question' do
  given(:user) { create(:user) }

  background do
    sign_in_user user
    visit root_path
  end

  scenario 'User adds file when asks question', js: true do
    click_on 'Ask something'
    fill_in 'Title', with: 'Test question'
    fill_in 'Tell about your question', with: 'text text text'
    click_on 'add task' # FIXME: double links (generated by gem for attach file)
    attach_file 'Choose File', "#{Rails.root}/spec/spec_helper.rb"
    click_on 'Create'

    expect(page).to have_link 'spec_helper.rb', href: '/uploads/attachment/file/1/spec_helper.rb'
  end
end
